version: "3.4"
services:
  todo:
    image: ng-grpc_backend:dev
    networks:
      - envoymesh
    build:
      context: backend
      target: dev
    depends_on:
      - proxy
    ports:
      - 50051:50051

  frontend:
    image: ng-grpc_frontend:dev
    networks:
      - envoymesh
    build:
      context: frontend
      target: dev
    depends_on:
      - todo
      - proxy
    ports:
      - 4200:4200

  proxy:
    image: envoyproxy/envoy-alpine
    networks:
      - envoymesh
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 8081:8081

networks:
  envoymesh: {}
